# Generated by Django 3.2.7 on 2021-10-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
